# Build stage
FROM node:18-alpine as build

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm i

# Copy the rest of the code
COPY . ./

# Build the app
RUN npm run build

# Expose port 3000
EXPOSE 3000

