version: "3.8"

services:
  db:
    image: mariadb:10.6
    container_name: mariadb-dev
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: nbweather
      MYSQL_USER: nbuser
      MYSQL_PASSWORD: nbpassword
    volumes:
      - mariadb_data:/var/lib/mysql

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: spring-api-dev
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:mariadb://db:3306/nbweather
      - SPRING_DATASOURCE_USERNAME=nbuser
      - SPRING_DATASOURCE_PASSWORD=nbpassword
    depends_on:
      - db

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: react-client-dev
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://localhost:8080
    depends_on:
      - api

volumes:
  mariadb_data:
