version: "3.8"

services:
  db:
    image: mariadb:10.6
    container_name: mariadb-dev
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: nbweather
      MYSQL_USER: nbuser
      MYSQL_PASSWORD: nbpassword
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: spring-api-dev
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=nbweather
      - DB_USERNAME=nbuser
      - DB_PASSWORD=nbpassword
    volumes:
      - ./backend:/app
      - ~/.m2:/root/.m2
    depends_on:
      - db

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: react-client-dev
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8080
    depends_on:
      - api

volumes:
  mariadb_data:
