version: "3.8"

services:
  db:
    image: mariadb:10.6
    container_name: mariadb-prod
    restart: always
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3307:3306"
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --skip-character-set-client-handshake
      --innodb-buffer-pool-size=256M
      --max-allowed-packet=64M
      --wait_timeout=28800
      --interactive_timeout=28800
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p${DB_ROOT_PASSWORD}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: node-api-prod
    restart: always
    env_file: .env
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mysql://${DB_USER}:${DB_PASSWORD}@db:3306/${DB_NAME}?connection_limit=5&pool_timeout=0
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    command: >
      sh -c "
        sleep 15 &&
        npx prisma migrate deploy &&
        npm start
      "

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: react-client-prod
    restart: always
    environment:
      - VITE_API_URL=${VITE_API_URL}
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  mariadb_data:
    external: true
