version: "3.8"

services:
  db:
    image: mariadb:10.6
    container_name: mariadb-dev
    restart: always
    env_file: .env.dev
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command:
      - --init-file
      - /docker-entrypoint-initdb.d/init.sql
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  prisma-migrate:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: prisma-migrate
    env_file: .env.dev
    environment:
      - DATABASE_URL=mysql://${DB_USER}:${DB_PASSWORD}@db:3306/${DB_NAME}
    depends_on:
      db:
        condition: service_healthy
    command: npx prisma migrate deploy

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ts-api-dev
    ports:
      - "8080:8080"
    env_file: .env.dev
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mysql://${DB_USER}:${DB_PASSWORD}@db:3306/${DB_NAME}
    depends_on:
      db:
        condition: service_healthy
      prisma-migrate:
        condition: service_completed_successfully
    command: sh -c "npx prisma generate && npm run dev"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: react-client-dev
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://localhost:8080
    depends_on:
      - api

volumes:
  mariadb_data:
